import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// PLACEHOLDER Firebase configuration.
///
/// This file is normally generated by the FlutterFire CLI. Run:
///
///   dart pub global activate flutterfire_cli
///   flutterfire configure
///
/// which overwrites this file with your real project values. Then set
/// `kFirebaseConfigured = true` in `lib/core/push/push_config.dart`.
///
/// While `kFirebaseConfigured` is false these values are never used.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'REPLACE_ME',
      appId: 'REPLACE_ME',
      messagingSenderId: 'REPLACE_ME',
      projectId: 'REPLACE_ME',
    );
  }
}
